### ISSUE TITLE
Documentation page does not exist yet

### ISSUE THREAD

**Issue by lucaswerkmeister** [Vesihiisi/Hauki#3]
[The footer of the tool](https://github.com/Vesihiisi/Hauki/blob/3067b0a97ec4ca3b420616af02e38b737105d901/templates/base.html#L36) links to a [documentation page](https://www.wikidata.org/wiki/User:Vesihiisi/Hauki), but it doesn’t exist yet.

**Comment by Vesihiisi** [comment]
I was probably [writing it](https://www.wikidata.org/wiki/User:Vesihiisi/Hauki) while you were typing in this ticket :grin:
